#' @title Time series plotting module (UI)
#' @description Based on a tidy \code{data.frame} of time series data, the module plots the series and allows for selecting series / groups of series to be plotted.
#' @param module_header_text \code{character}, defines some local module title.
#' @details This module shows the user the table generated by \code{\link{data_presentation_and_selection}}. \cr \cr
#' There are the following static UI elements: \cr
#' - \code{textOutput("site_header")} renders the title of the page \cr
#' - \code{actionButton("validate_and_proceed")} finishes work on the step and forces a move down the workflow \cr
#' - \code{DT::dataTableOutput("list_of_tags")} prints the names of the time series \code{tags} chosen by the user. 
#' It is from this table that elements for plotting are selected. Clicking on a series in the plot area highlights it in this table. \cr
#' - \code{DT::dataTableOutput("list_of_series")} where from the user picks individual series to be plotted. \cr
#' - the plotting area. Time series plots. \code{plotOutput("ts_plot")} or \code{plotly::plotlyOutput("ts_plot")}. \cr
#' - \code{textOutput("clicked_series")}: name of series that was selected by in in-plot click
#' \cr
#' There are the following dynamic UI elements, generated in \code{\link{time_series_plotting}}: \cr
#' - A \code{selectInput} (multiple) box with \code{value_types} which should be plotted, which are populated from the 
#' \code{value_type} column of \code{time_series_data} in the server function \code{\link{time_series_plotting}}. 
#' This is accompanied by a \code{checkBox} highlight option to highlight aggregated series in plots, and grey out the individual components.
#' \cr \cr
#' An alternative to generating is using \code{updateSomeElement} functions.
#' @seealso \code{\link{time_series_plotting}}
#' @export

time_series_plotting_ui <- function(id, module_header_text){
  ns <- NS(id)
  
  tagList(
    
    # data tables area
    fluidRow(
      tags$h1(module_header_text),
      
      sidebarLayout(
        sidebarPanel(
          # selectizeInput tag
          selectizeInput(ns("list_of_tags"), choices = NULL, 
                         label = "Choose tags", multiple = TRUE)
        ),
        
        mainPanel(
          # dataTable of series
          DT::dataTableOutput(ns("list_of_series"))
        )
      )
    ),
    
    # plot area
    fluidRow(
      sidebarLayout(
        sidebarPanel(
          # selectizeInput value type
          uiOutput(ns("value_type")),
          
          tags$br(),
          
          # selectizeInput frequency
          uiOutput(ns("frequency")),
          
          tags$br(),
          
          # checkBox highlight
          uiOutput(ns("highlight")),
          
          tags$br(),
          
          # textOutput of selected series
          # helpText("Selected series"),
          uiOutput(ns("help_clicked_series")),
          verbatimTextOutput(ns("clicked_series"))
        ),
        
        mainPanel(
          # plot
          plotOutput(ns("ts_plot"))
        )
      )
      
      
    )
  )
  
}